Gourmet Shop/Admin.WebApp/Controllers/OrdersController.cs
using GourmetShop.DataAccess.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Admin.WebApp.Controllers
{
    public class OrdersController : Controller
    {
        private readonly GourmetShopDbContext _context;

        public OrdersController(GourmetShopDbContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> IndexAsync()
        {
            
            var orders = await _context.Orders
                                       .AsNoTracking()
                                       .Include(o => o.UserInfo)
                                       .Include(o => o.OrderItems)
                                       .ThenInclude(oi => oi.Product)
                                       .ToListAsync();

            Console.WriteLine($"Orders count: {orders.Count}");
            return View(orders);
        }
    }
}

Gourmet Shop/Admin.WebApp/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using GourmetShop.DataAccess.Repositories;
using GourmetShop.DataAccess.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GourmetShop.DataAccess.Data;
using Microsoft.AspNetCore.Authorization;

namespace Admin.WebApp.Controllers
{

    public class ProductsController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly GourmetShopDbContext _context;
        //public IActionResult Index()
        //{
        //    return View();
        //}

        public ProductsController(IProductRepository productRepository, GourmetShopDbContext context)
        {
            _productRepository = productRepository;
            _context = context;
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var products = await _productRepository.GetAllAsync();
            return View(products);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult AddProduct()
        {
            var suppliers = _context.Suppliers?.ToList() ?? new List<Supplier>();
            var subcategories = _context.Subcategories?.ToList() ?? new List<Subcategory>();
            ViewBag.SupplierId = new SelectList(_context.Suppliers, "Id", "CompanyName");
            ViewBag.SubcategoryId = new SelectList(_context.Subcategories, "Id", "Name");
            return View(new Product());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> AddProduct(Product product)
        {
            //bind the supplier object to the product
            product.Supplier = _context.Suppliers.FirstOrDefault(s => s.Id == product.SupplierId);
            if (product.Supplier == null)
            {
                ModelState.AddModelError("SupplierId", "Invalid supplier selected.");
            }
            else
            {
                await _productRepository.AddAsync(product);
                return RedirectToAction("Index");
            }


            ViewBag.SupplierId = new SelectList(_context.Suppliers, "Id","CompanyName", product.SupplierId);
            ViewBag.SubcategoryId = new SelectList(_context.Subcategories, "Id", "Name", product.SubcategoryId);
            return View(product);
        }


        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Update([FromForm] Product product)
        {
            if (product == null) return BadRequest("Invalid product data.");

            if (!ModelState.IsValid)
            {
                return BadRequest($"Model state is invalid" + ModelState);
            }

            await _productRepository.UpdateAsync(product);
            return Ok(new { message = "Product updated" });
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var existingProduct = await _productRepository.GetAsync(id);
            if (existingProduct == null)
            {
                return NotFound("Product not found.");
            }
            

            await _productRepository.DeleteAsync(id);
            return Ok(new { message = "Product deleted" });
        }

        

       
    }


    
    
}

Gourmet Shop/Admin.WebApp/Controllers/SuppliersController.cs
using GourmetShop.DataAccess.Data;
using GourmetShop.DataAccess.Models;
using GourmetShop.DataAccess.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Admin.WebApp.Controllers
{
    public class SuppliersController : Controller
    {
        private readonly ISupplierRepository _supplierRepository;
        private readonly GourmetShopDbContext _context;

        public SuppliersController(ISupplierRepository supplierRepository, GourmetShopDbContext context)
        {
            _supplierRepository = supplierRepository;
            _context = context;
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var suppliers = await _supplierRepository.GetAllAsync();
            return View(suppliers);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult AddSupplier()
        {
            
            return View(new Supplier());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> AddSupplier(Supplier supplier)
        {
           
                await _supplierRepository.AddAsync(supplier);
                return RedirectToAction("Index");
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Update([FromForm] Supplier supplier)
        {
            if (supplier == null) return BadRequest("Invalid supplier.");
            var existingSupplier = await _supplierRepository.GetAsync(supplier.Id);
            if (existingSupplier == null) return NotFound("Supplier not found.");
            
            if (!ModelState.IsValid)
            {
                return BadRequest($"Model state is invalid" + ModelState);
            }

            _context.Entry(existingSupplier).State = Microsoft.EntityFrameworkCore.EntityState.Detached;

            await _supplierRepository.UpdateAsync(supplier);
            return Ok(new { message = "Supplier updated" });
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var existingProduct = await _supplierRepository.GetAsync(id);
            if (existingProduct == null)
            {
                return NotFound("Supplier not found.");
            }


            await _supplierRepository.DeleteAsync(id);
            return Ok(new { message = "Supplier deleted" });
        }
    }
}

Gourmet Shop/Admin.WebApp/Views/Shared/_Layout.cshtml
@using GourmetShop.DataAccess.Models
@using GourmetShop.DataAccess.Repositories
@inject IProductRepository ProductRepository
@inject ISupplierRepository SupplierRepository

<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Admin.WebApp</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Aboreto&family=Chivo:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Admin.WebApp.styles.css" asp-append-version="true" />

    @RenderSection("Styles", required: false)
   
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> GourmetShop Adminsitration</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        

						@if (User.Identity.IsAuthenticated)
						{
							<li class="nav-item">
								<a class="nav-link text-dark" asp-controller="Products" asp-action="Index">Products</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-controller="Suppliers" asp-action="Index">Suppliers</a>
							</li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Orders" asp-action="Index">Orders</a>
                            </li>
						}
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Admin.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>